config:
  provider: keycloak-oidc
  cookieName: mdapi-admin
  existingSecret: oauth2-proxy-admin-credentials 
  configFile: |-
    provider="keycloak-oidc"
    provider_display_name="MDAPI"
    redirect_url="https://auth.mdapi.ch/admin/oauth2/callback"
    oidc_issuer_url="https://idp.mdapi.org/realms/tilloch"
    skip_provider_button=true
    cookie_domains=["mdapi.ch"]
    whitelist_domains=[".mdapi.ch"]
    email_domains=["*"]
    allowed_roles=["mdapi-admin"]
sessionStorage:
  type: redis
  redis:
    existingSecret: oauth2-proxy-admin-credentials
    passwordKey: redis-password
redis:
  enabled: true
  architecture: standalone
  auth:
    existingSecret: oauth2-proxy-admin-credentials
    existingSecretPasswordKey: redis-password
ingress:
  enabled: true
  path: /admin
  hosts:
    - auth.mdapi.ch
  annotations:
    cert-manager.io/issuer: letsencrypt-prod
    flame.pawelmalak/type: app
    flame.pawelmalak/name: Whoami (admin)
    flame.pawelmalak/url: https://auth.mdapi.ch/admin/oauth2/userinfo
    flame.pawelmalak/category: Identity
    flame.pawelmalak/icon: account-question
    flame.pawelmalak/order: '245'
  tls:
    - secretName: auth-cert
      hosts:
        - auth.mdapi.ch
    