apiVersion: v1
kind: LimitRange
metadata:
  name: instance-manager-ceiling
  namespace: longhorn-system
spec:
  limits:
  - type: Container
    default:
      memory: 8Gi
    defaultRequest:
      memory: 256Mi
