apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: wg-dev
spec:
  refreshInterval: 1m0s
  secretStoreRef:
    kind: ClusterSecretStore
    name: cm-akeyless
  target:
    name: wg-dev
    creationPolicy: Owner
  data:
    - remoteRef:
        key: /mdapi/dev/vpn/wg-private-key
      secretKey: private-key
    - remoteRef:
        key: /mdapi/dev/vpn/wg-psk
      secretKey: psk
