apiVersion: apps/v1
kind: Deployment
metadata:
  name: snowflake-proxy
  namespace: snowflake-proxy
  annotations:
    keel.sh/policy: force
    keel.sh/match-tag: "true"
    keel.sh/trigger: poll
    keel.sh/pollSchedule: "@every 4h"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: snowflake-proxy
  template:
    metadata:
      labels:
        app: snowflake-proxy
    spec:
      containers:
      - name: snowflake-proxy
        image: thetorproject/snowflake-proxy:latest
        env:
        - name: TZ
          value: Europe/Zurich
        resources:
          requests:
            memory: 64Mi
            cpu: 50m
          limits:
            memory: 256Mi
            cpu: 500m
