apiVersion: v1
kind: Service
metadata:
  name: sftpgo
  namespace: spider3
  annotations:
    purelb.io/service-group: default
    purelb.io/address: 192.168.1.56
spec:
  type: LoadBalancer
  selector:
    app: spider3
  ports:
    - { name: sftp,  port: 22100, targetPort: 2022, protocol: TCP }
    - { name: ftp,   port: 22101, targetPort: 2121, protocol: TCP }
    - { name: pasv0, port: 22150, targetPort: 22150, protocol: TCP }
    - { name: pasv1, port: 22151, targetPort: 22151, protocol: TCP }
    - { name: pasv2, port: 22152, targetPort: 22152, protocol: TCP }
    - { name: pasv3, port: 22153, targetPort: 22153, protocol: TCP }
    - { name: pasv4, port: 22154, targetPort: 22154, protocol: TCP }
    - { name: pasv5, port: 22155, targetPort: 22155, protocol: TCP }
    - { name: pasv6, port: 22156, targetPort: 22156, protocol: TCP }
    - { name: pasv7, port: 22157, targetPort: 22157, protocol: TCP }
    - { name: pasv8, port: 22158, targetPort: 22158, protocol: TCP }
    - { name: pasv9, port: 22159, targetPort: 22159, protocol: TCP }
---
apiVersion: v1
kind: Service
metadata:
  name: sftpgo-web
  namespace: spider3
spec:
  type: ClusterIP
  selector:
    app: spider3
  ports:
    - { name: web, port: 8080, targetPort: 8080, protocol: TCP }
