apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: spider3
  namespace: spider3
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/modsecurity-transaction-id: "$request_id"
spec:
  ingressClassName: nginx
  rules:
    - host: spider3.ch
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: spider3
                port:
                  number: 80
    - host: www.spider3.ch
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: spider3
                port:
                  number: 80
    - host: dev.spider3.ch
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: spider3
                port:
                  number: 80
  tls:
    - hosts:
        - spider3.ch
        - www.spider3.ch
        - dev.spider3.ch
      secretName: spider3-cert
