apiVersion: apps/v1
kind: Deployment
metadata:
  name: joplin-mcp
  namespace: joplin
  annotations:
    keel.sh/policy: force
    keel.sh/match-tag: "true"
    keel.sh/trigger: poll
    keel.sh/pollSchedule: "@every 4h"
spec:
  selector:
    matchLabels:
      app: joplin-mcp
  replicas: 2
  template:
    metadata:
      labels:
        app: joplin-mcp
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchLabels:
                  app: joplin-mcp
              topologyKey: kubernetes.io/hostname
      containers:
      - name: joplin-mcp
        image: registry.mdapi.ch/mdapi/joplin-mcp:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: JOPLIN_SERVER_URL
          value: https://notes.mdapi.ch
        envFrom:
        - secretRef:
            name: joplin-mcp-env-secret
        resources:
          requests:
            cpu: 25m
            memory: 1Gi
          limits:
            memory: 1536Mi
      imagePullSecrets:
      - name: mdapi-registry
