apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: joplin
  namespace: joplin
  annotations:
    cert-manager.io/issuer: letsencrypt-prod
    flame.pawelmalak/type: app
    flame.pawelmalak/name: Joplin
    flame.pawelmalak/url: https://notes.mdapi.ch
    flame.pawelmalak/category: Collaboration
    flame.pawelmalak/icon: message-text
    flame.pawelmalak/order: '50'
    nginx.ingress.kubernetes.io/enable-modsecurity: "true"
    nginx.ingress.kubernetes.io/modsecurity-transaction-id: "$request_id"
    nginx.ingress.kubernetes.io/modsecurity-snippet: |
      SecRuleEngine DetectionOnly
      Include /etc/nginx/owasp-modsecurity-crs/nginx-modsecurity.conf
spec:
  ingressClassName: nginx
  rules:
    - host: notes.mdapi.ch
      http:
        paths:
          - backend:
              service:
                name: joplin
                port:
                  number: 22300
            path: /
            pathType: Prefix
  tls:
    - hosts:
      - notes.mdapi.ch
      secretName: joplin-cert
