csiDriver:
  name: "ch.tillo.home.salt.nfs"
  fsGroupPolicy: File

storageClasses:
  - name: salt-nfs
    defaultClass: false
    reclaimPolicy: Delete
    volumeBindingMode: Immediate
    allowVolumeExpansion: true
    parameters:
      fsType: nfs
    annotations:
      cdi.harvesterhci.io/storageProfileCloneStrategy: snapshot
      cdi.harvesterhci.io/storageProfileVolumeModeAccessModes: '{"Filesystem":["ReadWriteMany"]}'
      cdi.harvesterhci.io/storageProfileVolumeSnapshotClass: salt-nfs
      cdi.harvesterhci.io/filesystemOverhead: '0.05'
    mountOptions:
      - noatime
      - nfsvers=4
    secrets:
      provisioner-secret:
      controller-publish-secret:
      node-stage-secret:
      node-publish-secret:
      controller-expand-secret:

volumeSnapshotClasses:
  - name: salt-nfs
    secrets:
      snapshotter-secret:

driver:
  existingConfigSecret: salt-nfs-driver-config
  config:
    driver: freenas-nfs
    