apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: open-terminal-secret
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: cm-akeyless
  target:
    name: open-terminal-secret
    creationPolicy: Owner
  data:
    - remoteRef:
        key: /mdapi/openwebui/open-terminal/api_key
      secretKey: API_KEY
