apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: wp-salts
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: cm-akeyless
  target:
    name: wp-salts
    creationPolicy: Owner
  data:
    - remoteRef:
        key: /mdapi/textopolis/wp-salts
        property: AUTH_KEY
      secretKey: AUTH_KEY
    - remoteRef:
        key: /mdapi/textopolis/wp-salts
        property: SECURE_AUTH_KEY
      secretKey: SECURE_AUTH_KEY
    - remoteRef:
        key: /mdapi/textopolis/wp-salts
        property: LOGGED_IN_KEY
      secretKey: LOGGED_IN_KEY
    - remoteRef:
        key: /mdapi/textopolis/wp-salts
        property: NONCE_KEY
      secretKey: NONCE_KEY
    - remoteRef:
        key: /mdapi/textopolis/wp-salts
        property: AUTH_SALT
      secretKey: AUTH_SALT
    - remoteRef:
        key: /mdapi/textopolis/wp-salts
        property: SECURE_AUTH_SALT
      secretKey: SECURE_AUTH_SALT
    - remoteRef:
        key: /mdapi/textopolis/wp-salts
        property: LOGGED_IN_SALT
      secretKey: LOGGED_IN_SALT
    - remoteRef:
        key: /mdapi/textopolis/wp-salts
        property: NONCE_SALT
      secretKey: NONCE_SALT
