apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keel-mail
spec:
  refreshInterval: 1m0s

  secretStoreRef:
    kind: ClusterSecretStore
    name: cm-akeyless

  target:
    name: keel-mail
    creationPolicy: Owner
    template:
      data:
        MAIL_SMTP_SERVER: mail.mdapi.ch
        MAIL_SMTP_PORT: "25"
        MAIL_FROM: keel@mdapi.tillo.ch
        MAIL_TO: "{{ .pushoverEmail }}"

  data:
    - remoteRef:
        key: /mdapi/keel/pushover-email
      secretKey: pushoverEmail
