apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: cm-akeyless
spec:
  provider:
    akeyless:
      akeylessGWApiURL: https://cm.mdapi.ch/akeyless-api/v2
      authSecretRef:
        secretRef:
          accessID:
            name: akeyless
            key: accessId
            namespace: external-secrets
          accessType:
            name: akeyless
            key: accessType
            namespace: external-secrets
          accessTypeParam:
            name: akeyless
            key: accessTypeParam
            namespace: external-secrets
