apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flame
  namespace: flame
  annotations:
    # Figure out how to do this with RFC-2136 (https://cert-manager.io/docs/configuration/acme/dns01/rfc2136/)
    #cert-manager.io/issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  rules:
    - host: dev.mdapi.ch
      http:
        paths:
          - backend:
              service:
                name: flame
                port:
                  number: 5005
            path: /
            pathType: Prefix
  tls:
    - hosts:
      - dev.mdapi.ch
      secretName: flame-cert
