apiVersion: apps/v1
kind: Deployment
metadata:
  name: flame
  namespace: flame
spec:
  selector:
    matchLabels:
      app: flame
  replicas: 1
  template:
    metadata:
      labels:
        app: flame
    spec:
      containers:
      - name: flame
        image: ghcr.io/fdarveau/flame
        ports:
        - containerPort: 80
