apiVersion: v1
kind: ConfigMap
metadata:
  name: flame-patches
  namespace: flame
data:
  dot-name-bug.patch: |
    --- controllers/apps/docker-orig/useKubernetes.js
    +++ controllers/apps/docker/useKubernetes.js
    @@ -60,7 +60,7 @@
             /^app/.test(annotations['flame.pawelmalak/type'])
           ) {

    -        const names = annotations['flame.pawelmalak/.name'].split(';');
    +        const names = annotations['flame.pawelmalak/name'].split(';');
             const urls = annotations['flame.pawelmalak/url'].split(';');
             const categoriesLabels = annotations['flame.pawelmalak/category'] ? annotations['flame.pawelmalak/category'].split(';') : [];
             const orders = annotations['flame.pawelmalak/order'] ? annotations['flame.pawelmalak/order'].split(';') : [];
  category-bug.patch: |
    --- controllers/apps/docker-orig/useKubernetes.js
    +++ controllers/apps/docker/useKubernetes.js
    @@ -85,12 +85,6 @@
                 orderId: orders[i] || 500,
               });
             }
    -
    -        kubernetesApps.push({
    -          name: annotations['flame.pawelmalak/name'],
    -          url: annotations['flame.pawelmalak/url'],
    -          icon: annotations['flame.pawelmalak/icon'] || 'kubernetes',
    -        });
           }
         }  
