apiVersion: v1
kind: Service
metadata:
  name: opennic-tier2
  namespace: opennic
spec:
  type: LoadBalancer
  loadBalancerClass: metallb
  loadBalancerIP: 192.168.1.44
  externalTrafficPolicy: Local
  selector:
    app: opennic-tier2
  ports:
  - name: nameserver-udp
    port: 53
    protocol: UDP
    targetPort: 53
  - name: nameserver-tcp
    port: 53
    protocol: TCP
    targetPort: 53
