apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: lam-env-secret
spec:
  refreshInterval: 1m0s

  secretStoreRef:
    kind: ClusterSecretStore
    name: cm-akeyless

  target:
    name: lam-env-secret
    creationPolicy: Owner

  data:
    - remoteRef:
        key: /mdapi/openldap/lam-env-secret/LAM_PASSWORD
      secretKey: LAM_PASSWORD
    - remoteRef:
        key: /mdapi/openldap/lam-env-secret/LDAP_ADMIN_PASSWORD
      secretKey: LDAP_ADMIN_PASSWORD
