apiVersion: v1
kind: Service
metadata:
  name: trapeye-clusterip
  namespace: honeypot
spec:
  selector:
    app: trapeye-clusterip
  ports:
    - name: ftp
      port: 21
    - name: ssh
      port: 22
    - name: smtp
      port: 25
    - name: smtps
      port: 465
    - name: http
      port: 80
    - name: https
      port: 443
    - name: ldap
      port: 389
    - name: ldaps
      port: 636
    - name: rdp
      port: 3389
    - name: postgresql
      port: 5432
  type: ClusterIP
