apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: trapeye
  namespace: honeypot
  annotations:
    cert-manager.io/issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  rules:
    - host: shop.mdapi.ch
      http:
        paths:
          - backend:
              service:
                name: trapeye-clusterip
                port:
                  number: 80
            path: /
            pathType: Prefix
  tls:
    - hosts:
      - shop.mdapi.ch
      secretName: trapeye-cert
