apiVersion: apps/v1
kind: Deployment
metadata:
  name: trapeye-nodeport
  namespace: honeypot
spec:
  selector:
    matchLabels:
      app: trapeye-nodeport
  replicas: 1
  template:
    metadata:
      labels:
        app: trapeye-nodeport
    spec:
      containers:
      - name: trapeye
        image: ghcr.io/anantis-security/trapeye:1.4.1
        imagePullPolicy: IfNotPresent
        resources: {}
        ports:
        - name: ftp
          containerPort: 21
        - name: ssh
          containerPort: 22
        - name: smtp
          containerPort: 25
        - name: smtps
          containerPort: 465
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
        - name: ldap
          containerPort: 389
        - name: ldaps
          containerPort: 636
        - name: rdp
          containerPort: 3389
        - name: postgresql
          containerPort: 5432
        env:
        - name: TZ
          value: Europe/Zurich
        - name: TRAPEYE_UUID
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.uid
        envFrom:
        - secretRef:
            name: trapeye-env-secret
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trapeye-clusterip
  namespace: honeypot
spec:
  selector:
    matchLabels:
      app: trapeye-clusterip
  replicas: 1
  template:
    metadata:
      labels:
        app: trapeye-clusterip
    spec:
      containers:
      - name: trapeye
        image: ghcr.io/anantis-security/trapeye:1.4.1
        imagePullPolicy: IfNotPresent
        resources: {}
        ports:
        - name: ftp
          containerPort: 21
        - name: ssh
          containerPort: 22
        - name: smtp
          containerPort: 25
        - name: smtps
          containerPort: 465
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
        - name: ldap
          containerPort: 389
        - name: ldaps
          containerPort: 636
        - name: rdp
          containerPort: 3389
        - name: postgresql
          containerPort: 5432
        env:
        - name: TZ
          value: Europe/Zurich
        - name: TRAPEYE_UUID
          valueFrom:
            fieldRef:
              fieldPath: metadata.uid
        envFrom:
        - secretRef:
            name: trapeye-env-secret
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trapeye-loadbalancer
  namespace: honeypot
spec:
  selector:
    matchLabels:
      app: trapeye-loadbalancer
  replicas: 1
  template:
    metadata:
      labels:
        app: trapeye-loadbalancer
    spec:
      containers:
      - name: trapeye
        image: ghcr.io/anantis-security/trapeye:1.4.1
        imagePullPolicy: IfNotPresent
        resources: {}
        ports:
        - name: ftp
          containerPort: 21
        - name: ssh
          containerPort: 22
        - name: smtp
          containerPort: 25
        - name: smtps
          containerPort: 465
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
        - name: ldap
          containerPort: 389
        - name: ldaps
          containerPort: 636
        - name: rdp
          containerPort: 3389
        - name: postgresql
          containerPort: 5432
        env:
        - name: TZ
          value: Europe/Zurich
        - name: TRAPEYE_UUID
          valueFrom:
            fieldRef:
              fieldPath: metadata.uid
        envFrom:
        - secretRef:
            name: trapeye-env-secret
