# phase2 2026-08-03: repoint config-storage to the ceph-block PVC (see *-ceph-pvc.yaml)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstream-leader
spec:
  template:
    spec:
      volumes:
        - name: config-storage
          persistentVolumeClaim:
            claimName: leader-config-claim-ceph
