apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  annotations:
    keel.sh/policy: minor
    keel.sh/trigger: poll
    keel.sh/pollSchedule: "@every 4h"
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: mirror.gcr.io/redis:7
          imagePullPolicy: Always
          ports:
            - containerPort: 6379
