apiVersion: v1
kind: Service
metadata:
  name: technitium-primary
  namespace: technitium
spec:
  selector:
    app: technitium-primary
  ports:
  - name: http
    port: 5380
    targetPort: 5380
  - name: dns-tcp
    port: 53
    targetPort: 53
    protocol: TCP
  - name: dns-udp
    port: 53
    targetPort: 53
    protocol: UDP
  type: ClusterIP
