apiVersion: akri.sh/v0
kind: Configuration
metadata:
  name: akri-home-assistant
spec:
  capacity: 1
  discoveryHandler:
    discoveryDetails: |
      udevRules:
      - ATTRS{product}=="Home Assistant Connect ZBT-1"
    name: udev
