certificate: dovecot-cert
deployment:
  env:
    OVERRIDE_HOSTNAME: mail.mdapi.ch
    TZ: Europe/Zurich
persistent_volume_claims:
  mail-config:
    size: 1G
    storageClass: harvester-longhorn-2replicas
  mail-data:
    size: 100G
    storageClass: harvester-longhorn-2replicas
  mail-state:
    size: 10G
    storageClass: harvester-longhorn-2replicas
  mail-log:
    size: 20G
    storageClass: harvester-longhorn-2replicas
keel:
  policy: minor
  trigger: poll
  images:
    - repository: image.repository
      tag: image.tag
