certificate: mail-cert
deployment:
  env:
    ACCOUNT_PROVISIONER: LDAP
    LOG_LEVEL: info
    SUPERVISOR_LOGLEVEL: info
    ENABLE_CLAMAV: 1
    POSTMASTER_ADDRESS: tillo@tillo.ch
    OVERRIDE_HOSTNAME: mail.mdapi.ch
    TZ: Europe/Zurich
    RSPAMD_LEARN: 1
    RSPAMD_CHECK_AUTHENTICATED: 1
    ENABLE_MANAGESIEVE: 1
    VIRUSMAILS_DELETE_DELAY: 30
    POSTFIX_MESSAGE_SIZE_LIMIT: "102400000"
    PFLOGSUMM_TRIGGER: logrotate
    PFLOGSUMM_RECIPIENT: tillo@tillo.ch
    LOGWATCH_INTERVAL: weekly
    LOGWATCH_RECIPIENT: tillo@tillo.ch
    LDAP_SEARCH_BASE: dc=mdapi,dc=ch
    LDAP_QUERY_FILTER_USER: "(&(objectClass=room)(cn=%s)(dn=*,ou=People,dc=mdapi,dc=ch))"
    LDAP_QUERY_FILTER_GROUP: "(&(objectClass=room)(cn=%s)(dn=*,ou=group,dc=mdapi,dc=ch))"
    LDAP_QUERY_FILTER_ALIAS: "(&(objectClass=room)(cn=%s)(dn=*,ou=alias,dc=mdapi,dc=ch))"
    LDAP_QUERY_FILTER_DOMAIN: "(&(objectClass=room)(cn=%s)(dn=*,ou=domain,dc=mdapi,dc=ch))"
    DOVECOT_USER_FILTER: "(&(objectClass=room)(cn=%u)(dn=*,ou=People,dc=mdapi,dc=ch))"
    DOVECOT_PASS_FILTER: "(&(objectClass=posixAccount)(mail=%u)(dn=*,ou=People,dc=mdapi,dc=ch))"
    DOVECOT_USER_ATTRS: "uidNumber=uid,=gid=5000,description=home=/var/mail/%$"
    DOVECOT_PASS_ATTRS: "userPassword=password"
    DOVECOT_AUTH_BIND: no
    ENABLE_SASLAUTHD: 1
    SASLAUTHD_MECHANISMS: rimap
    SASLAUTHD_MECH_OPTIONS: "127.0.0.1"
  secretEnvironments:
  - docker-mailserver-env-secret
persistent_volume_claims:
  mail-config:
    size: 1G
    storageClass: harvester-longhorn-2replicas
  mail-data:
    size: 100G
    storageClass: harvester-longhorn-2replicas
  mail-state:
    size: 10G
    storageClass: harvester-longhorn-2replicas
  mail-log:
    size: 20G
    storageClass: harvester-longhorn-2replicas
service:
  type: LoadBalancer
rspamd:
  ingress:
    enabled: true
    annotations:
      cert-manager.io/issuer: letsencrypt-prod
    host: rspamd.mdapi.ch
    tls:
      enabled: true
      secret: rspamd-cert
dovecot:
  fullTextSearch:
    enabled: true
extraDeploy:
- apiVersion: external-secrets.io/v1
  kind: ExternalSecret
  metadata:
    name: docker-mailserver-env-secret
  spec:
    refreshInterval: 1m0s

    secretStoreRef:
      kind: ClusterSecretStore
      name: cm-akeyless

    target:
      name: docker-mailserver-env-secret
      creationPolicy: Owner

    data:
      - remoteRef:
          key: /mdapi/mail/docker-mailserver-env-secret/DOVECOT_URIS
        secretKey: DOVECOT_URIS
      - remoteRef:
          key: /mdapi/mail/docker-mailserver-env-secret/LDAP_BIND_DN
        secretKey: LDAP_BIND_DN
      - remoteRef:
          key: /mdapi/mail/docker-mailserver-env-secret/LDAP_BIND_PW
        secretKey: LDAP_BIND_PW
keel:
  policy: minor
  trigger: poll
  images:
    - repository: image.repository
      tag: image.tag
