certificate: mail-cert
deployment:
  env:
    ACCOUNT_PROVISIONER: FILE
    LOG_LEVEL: info
    SUPERVISOR_LOGLEVEL: info
    ENABLE_CLAMAV: 1
    ENABLE_OPENDKIM: 1
    ENABLE_OPENDMARC: 1
    POSTMASTER_ADDRESS: tillo@tillo.ch
    OVERRIDE_HOSTNAME: mail.mdapi.ch
    TZ: Europe/Zurich
    RSPAMD_LEARN: 1
    RSPAMD_CHECK_AUTHENTICATED: 1
    ENABLE_MANAGESIEVE: 1
    VIRUSMAILS_DELETE_DELAY: 30
    POSTFIX_MESSAGE_SIZE_LIMIT: "102400000"
    PFLOGSUMM_TRIGGER: logrotate
    PFLOGSUMM_RECIPIENT: tillo@tillo.ch
    LOGWATCH_INTERVAL: weekly
    LOGWATCH_RECIPIENT: tillo@tillo.ch
persistent_volume_claims:
  mail-config:
    size: 1G
    storageClass: harvester-longhorn-2replicas
  mail-data:
    size: 100G
    storageClass: harvester-longhorn-2replicas
  mail-state:
    size: 10G
    storageClass: harvester-longhorn-2replicas
  mail-log:
    size: 20G
    storageClass: harvester-longhorn-2replicas
service:
  type: LoadBalancer
keel:
  policy: minor
  trigger: poll
  images:
    - repository: image.repository
      tag: image.tag
