apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud-aio-notify-push
  namespace: envuassu
spec:
  template:
    spec:
      containers:
        - name: nextcloud-aio-notify-push
          env:
            - name: POSTGRES_PASSWORD
              $patch: delete
            - name: REDIS_HOST_PASSWORD
              $patch: delete
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: io.kompose.service
                operator: In
                values:
                - nextcloud-aio-nextcloud
            topologyKey: "kubernetes.io/hostname"
