apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud-aio-redis
  namespace: envuassu
spec:
  template:
    spec:
      priorityClassName: mdapi-critical
      containers:
        - name: nextcloud-aio-redis
          imagePullPolicy: IfNotPresent
          env:
            - name: REDIS_HOST_PASSWORD
              $patch: delete
          envFrom:
            - secretRef:
                name: nextcloud-aio-env-secret
