apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud-aio-database
  namespace: envuassu
spec:
  template:
    spec:
      containers:
        - name: nextcloud-aio-database
          env:
            - name: POSTGRES_PASSWORD
              $patch: delete
          envFrom:
            - secretRef:
                name: nextcloud-aio-env-secret
