apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud-aio-onlyoffice
  namespace: envuassu
spec:
  template:
    spec:
      containers:
        - name: nextcloud-aio-onlyoffice
          env:
            - name: JWT_SECRET
              $patch: delete
          envFrom:
            - secretRef:
                name: nextcloud-aio-env-secret
