apiVersion: v1
kind: ConfigMap
metadata:
  name: named-conf
  namespace: nameserver
data:
  named.conf: |
    include "/etc/bind/tsig.key";
    include "/etc/bind/rndc.key";

    controls {
      inet 127.0.0.1 port 953 allow { 127.0.0.1; } keys { "rndc-key"; };
    };

    options {
      directory "/var/lib/bind";
      listen-on { any; };
      listen-on port 5353 proxy plain { any; };
      listen-on-v6 { any; };
      allow-query { any; };
      allow-recursion { none; };
      allow-proxy { 192.168.1.0/24; 10.0.0.0/8; };
      recursion no;
      dnssec-validation auto;
      auth-nxdomain no;
    };

    logging {
      channel default_log {
        stderr;
        severity info;
        print-time yes;
        print-severity yes;
        print-category yes;
      };
      category default { default_log; };
      category queries { default_log; };
    };

    zone "tillo.ch" {
      type master;
      file "/var/lib/bind/tillo.ch";
      allow-transfer { 69.65.50.192; 204.42.254.5; };
      allow-update { key "mdapi"; };
    };

    zone "mdapi.ch" {
      type master;
      file "/var/lib/bind/mdapi.ch";
      allow-transfer { 69.65.50.192; 204.42.254.5; };
    };

    zone "mdapi.org" {
      type master;
      file "/var/lib/bind/mdapi.org";
      allow-transfer { 69.65.50.192; 204.42.254.5; };
    };

    zone "textopolis.net" {
      type master;
      file "/var/lib/bind/textopolis.net";
      allow-transfer { 69.65.50.192; 204.42.254.5; };
    };

    zone "spider3.ch" {
      type master;
      file "/var/lib/bind/spider3.ch";
      allow-transfer { 69.65.50.192; 204.42.254.5; };
    };

    zone "lithia.eu" {
      type master;
      file "/var/lib/bind/lithia.eu";
      allow-transfer { 69.65.50.192; 204.42.254.5; };
    };

    zone "ivodellambrogio.ch" {
      type master;
      file "/var/lib/bind/ivodellambrogio.ch";
      allow-transfer { 69.65.50.192; 204.42.254.5; };
    };

    zone "dellambrogio.ch" {
      type master;
      file "/var/lib/bind/dellambrogio.ch";
      allow-transfer { 69.65.50.192; 204.42.254.5; };
    };

    zone "dellambrogio.com" {
      type master;
      file "/var/lib/bind/dellambrogio.com";
      allow-transfer { 69.65.50.192; 204.42.254.5; };
    };

    zone "dellambrogio.net" {
      type master;
      file "/var/lib/bind/dellambrogio.net";
      allow-transfer { 69.65.50.192; 204.42.254.5; };
    };

    zone "dellambrogio.org" {
      type master;
      file "/var/lib/bind/dellambrogio.org";
      allow-transfer { 69.65.50.192; 204.42.254.5; };
    };

    zone "dellambrogio.info" {
      type master;
      file "/var/lib/bind/dellambrogio.info";
      allow-transfer { 69.65.50.192; 204.42.254.5; };
    };

    zone "coiffuredreams.ch" {
      type master;
      file "/var/lib/bind/coiffuredreams.ch";
      allow-transfer { 69.65.50.192; 204.42.254.5; };
    };

    zone "coders.ch" {
      type master;
      file "/var/lib/bind/coders.ch";
      allow-transfer { 69.65.50.192; 204.42.254.5; };
    };

    zone "1.168.192.in-addr.arpa" {
      type master;
      file "/var/lib/bind/1.168.192.in-addr.arpa";
      allow-transfer { 69.65.50.192; 204.42.254.5; };
    };

    zone "48-63.128.3.31.in-addr.arpa" {
      type master;
      file "/var/lib/bind/48-63.128.3.31.in-addr.arpa";
      allow-transfer { 69.65.50.192; 204.42.254.5; };
    };

    zone "9.e.1.0.4.0.5.0.d.0.d.0.a.2.ip6.arpa" {
      type master;
      file "/var/lib/bind/9.e.1.0.4.0.5.0.d.0.d.0.a.2.ip6.arpa";
      allow-transfer { 69.65.50.192; 204.42.254.5; };
    };

    zone "dynamic.home.tillo.ch" {
      type master;
      file "/var/lib/bind/dynamic.home.tillo.ch";
      allow-transfer { 69.65.50.192; 204.42.254.5; };
      allow-update { key "mdapi"; };
    };
