apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: akeyless
spec:
  refreshInterval: 1h

  secretStoreRef:
    kind: ClusterSecretStore
    name: cm-akeyless

  target:
    name: akeyless
    creationPolicy: Owner

  dataFrom:
    - extract:
        key: /pepper/external-secrets/akeyless
