apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-assistant
  namespace: home-assistant
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: home-assistant
  replicas: 1
  template:
    metadata:
      labels:
        app: home-assistant
    spec:
      containers:
      - name: home-assistant
        image: ghcr.io/home-assistant/home-assistant
        securityContext:
          privileged: true
        ports:
        - containerPort: 8123
#        command: ['/bin/sh']
#        args:
#        - '+x'
#        - '-c'
#        - >-
#          udevd -d
#          && sleep 20
#          && [ -c "/dev/ttyUSB0" ]
#          && /run/s6/legacy-services/home-assistant/run
#          || apk add --no-cache eudev
#          ; /run/s6/legacy-services/home-assistant/run
#          ; sleep infinity
        env:
        - name: TZ
          value: Europe/Zurich
        envFrom:
        - secretRef:
            name: home-assistant-env-secret
        volumeMounts:
        - name: home-assistant-data
          mountPath: /config
        - name: home-assistant-config
          mountPath: /config/configuration.yaml
          subPath: configuration.yaml
        - name: home-assistant-secrets
          mountPath: /config/secrets.yaml
          subPath: secrets.yaml
        resources:
          limits:
            akri.sh/akri-home-assistant: "1"
          requests:
            akri.sh/akri-home-assistant: "1"
      volumes:
      - name: home-assistant-data
        persistentVolumeClaim:
          claimName: home-assistant-data
      - name: home-assistant-config
        configMap:
          name: home-assistant-config
      - name: home-assistant-secrets
        secret:
          secretName: home-assistant-secrets
