apiVersion: v1
kind: ConfigMap
metadata:
  name: home-assistant-config
  namespace: home-assistant
data:
  configuration.yaml: |
    default_config:
    
    frontend:
      themes: !include_dir_merge_named themes
    
    tts:
      - platform: google_translate
    
    automation: !include automations.yaml
    script: !include scripts.yaml
    scene: !include scenes.yaml
    
    http:
      cors_allowed_origins:
        - https://home.dev.mdapi.ch
      use_x_forwarded_for: true
      trusted_proxies:
        - 10.0.0.0/8
        - 172.16.0.0/12
        - 192.168.0.0/16
      ip_ban_enabled: true
      login_attempts_threshold: 5

    command_line:
      - sensor:
        name: Home Assistant DB size
        scan_interval: 3600
        command_timeout: 30
        command: "bash -c 'du -shm /config/home-assistant_v2.db | cut -f1'"
        unit_of_measurement: MB
        value_template: "{{ value if is_number(value) }}"
