apiVersion: v1
kind: Service
metadata:
  name: squid
  namespace: squid
spec:
  selector:
    app: squid
  ports:
    - name: https-proxy
      port: 443
      protocol: TCP
      targetPort: 443
  type: LoadBalancer
  loadBalancerIP: 192.168.1.50
