apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: diun-pushover
spec:
  refreshInterval: 1m0s

  secretStoreRef:
    kind: ClusterSecretStore
    name: cm-akeyless

  target:
    name: diun-pushover
    creationPolicy: Owner
    template:
      data:
        DIUN_NOTIF_PUSHOVER_TOKEN: "{{ .token }}"
        DIUN_NOTIF_PUSHOVER_RECIPIENT: "{{ .recipient }}"

  data:
    - remoteRef:
        key: /mdapi/certspotter/certspotter-env-secret/CS_PUSHOVER_TOKEN
      secretKey: token
    - remoteRef:
        key: /mdapi/certspotter/certspotter-env-secret/CS_PUSHOVER_USER
      secretKey: recipient
