apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nut-creds
spec:
  refreshInterval: 1m0s

  secretStoreRef:
    kind: ClusterSecretStore
    name: cm-akeyless

  target:
    name: nut-creds
    creationPolicy: Owner

  data:
    - remoteRef:
        key: /mdapi/ups/nut/admin-password
      secretKey: admin_password
    - remoteRef:
        key: /mdapi/ups/nut/monuser-password
      secretKey: mon_password
