apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: infomaniak-api-credentials
spec:
  refreshInterval: 1m0s

  secretStoreRef:
    kind: ClusterSecretStore
    name: cm-akeyless

  target:
    name: infomaniak-api-credentials
    creationPolicy: Owner

  data:
    - remoteRef:
        key: /mdapi/envuassu/infomaniak-api-credentials/api-token
      secretKey: api-token
