apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nextcloud-aio-env-secret
spec:
  refreshInterval: 1m0s

  secretStoreRef:
    kind: ClusterSecretStore
    name: cm-akeyless

  target:
    name: nextcloud-aio-env-secret
    creationPolicy: Owner

  data:
    - remoteRef:
        key: /mdapi/envuassu/nextcloud-aio-env-secret/POSTGRES_PASSWORD
      secretKey: POSTGRES_PASSWORD
    - remoteRef:
        key: /mdapi/envuassu/nextcloud-aio-env-secret/FULLTEXTSEARCH_PASSWORD
      secretKey: FULLTEXTSEARCH_PASSWORD
    - remoteRef:
        key: /mdapi/envuassu/nextcloud-aio-env-secret/IMAGINARY_SECRET
      secretKey: IMAGINARY_SECRET
    - remoteRef:
        key: /mdapi/envuassu/nextcloud-aio-env-secret/ADMIN_PASSWORD
      secretKey: ADMIN_PASSWORD
    - remoteRef:
        key: /mdapi/envuassu/nextcloud-aio-env-secret/ONLYOFFICE_SECRET
      secretKey: ONLYOFFICE_SECRET
    - remoteRef:
        key: /mdapi/envuassu/nextcloud-aio-env-secret/JWT_SECRET
      secretKey: JWT_SECRET
    - remoteRef:
        key: /mdapi/envuassu/nextcloud-aio-env-secret/REDIS_HOST_PASSWORD
      secretKey: REDIS_HOST_PASSWORD
    - remoteRef:
        key: /mdapi/envuassu/nextcloud-aio-env-secret/SIGNALING_SECRET
      secretKey: SIGNALING_SECRET
    - remoteRef:
        key: /mdapi/envuassu/nextcloud-aio-env-secret/INTERNAL_SECRET
      secretKey: INTERNAL_SECRET
    - remoteRef:
        key: /mdapi/envuassu/nextcloud-aio-env-secret/TURN_SECRET
      secretKey: TURN_SECRET
