apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: coiffuredreams
  namespace: coiffuredreams
  annotations:
    cert-manager.io/issuer: letsencrypt-prod
    flame.pawelmalak/type: app
    flame.pawelmalak/name: Coiffure Dreams
    flame.pawelmalak/url: https://coiffuredreams.ch
    flame.pawelmalak/category: Web Hosting
    flame.pawelmalak/icon: web
    flame.pawelmalak/order: '10'
    nginx.ingress.kubernetes.io/enable-modsecurity: "true"
    nginx.ingress.kubernetes.io/modsecurity-transaction-id: "$request_id"
    nginx.ingress.kubernetes.io/modsecurity-snippet: |
      SecRuleEngine On
      SecAuditLogType Serial
      SecAuditLogFormat JSON
      SecAuditLog /dev/stdout
      Include /etc/nginx/owasp-modsecurity-crs/nginx-modsecurity.conf
spec:
  ingressClassName: nginx
  rules:
    - host: coiffuredreams.ch
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: coiffuredreams
                port:
                  number: 80
    - host: www.coiffuredreams.ch
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: coiffuredreams
                port:
                  number: 80
  tls:
    - hosts:
        - coiffuredreams.ch
        - www.coiffuredreams.ch
      secretName: coiffuredreams-cert
