apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
  namespace: coiffuredreams
spec:
  selector:
    matchLabels:
      app: mariadb
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
        - name: mariadb
          image: mariadb:10.11
          env:
            - name: MARIADB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: MARIADB_ROOT_PASSWORD
            - name: MARIADB_DATABASE
              value: coiffuredreams
            - name: MARIADB_USER
              value: coiffuredreams
            - name: MARIADB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DB_PASSWORD
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: db-data
              mountPath: /var/lib/mysql
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              memory: 512Mi
      volumes:
        - name: db-data
          persistentVolumeClaim:
            claimName: db-data
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb
  namespace: coiffuredreams
spec:
  selector:
    app: mariadb
  ports:
    - port: 3306
      targetPort: 3306
