apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: akri-self-heal
rules:
  - apiGroups: ["akri.sh"]
    resources: ["instances"]
    verbs: ["get", "list", "delete"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "delete"]
