apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: akri-self-heal
  namespace: home-assistant
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "delete"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["get", "list"]
