apiVersion: akri.sh/v0
kind: Configuration
metadata:
  name: akri-chrony
spec:
  capacity: 1
  discoveryHandler:
    discoveryDetails: |
      udevRules:
      - ATTRS{product}=="USB-Serial Controller D"
    name: udev
