apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: appdaemon
  namespace: appdaemon
  annotations:
    cert-manager.io/issuer: letsencrypt-prod
    flame.pawelmalak/type: app
    flame.pawelmalak/name: AppDaemon
    flame.pawelmalak/url: https://appdaemon.mdapi.ch
    flame.pawelmalak/category: Domotics
    flame.pawelmalak/icon: cog-transfer
    flame.pawelmalak/order: '15'
    nginx.ingress.kubernetes.io/auth-response-headers: Authorization
    nginx.ingress.kubernetes.io/auth-signin: https://auth.mdapi.ch/admin/oauth2/start?rd=https://$host$escaped_request_uri
    nginx.ingress.kubernetes.io/auth-url: https://auth.mdapi.ch/admin/oauth2/auth
spec:
  ingressClassName: nginx
  rules:
    - host: appdaemon.mdapi.ch
      http:
        paths:
          - backend:
              service:
                name: appdaemon
                port:
                  number: 80
            path: /
            pathType: Prefix
  tls:
    - hosts:
      - appdaemon.mdapi.ch
      secretName: appdaemon-cert
