apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: appdaemon
  namespace: appdaemon
  annotations:
    cert-manager.io/issuer: letsencrypt-prod
    flame.pawelmalak/type: app
    flame.pawelmalak/name: AppDaemon
    flame.pawelmalak/url: https://appdaemon.mdapi.ch
    flame.pawelmalak/category: Domotics
    flame.pawelmalak/icon: cog-transfer
    flame.pawelmalak/order: '20'
    nginx.ingress.kubernetes.io/auth-response-headers: Authorization
    nginx.ingress.kubernetes.io/auth-signin: https://auth.mdapi.ch/admin/oauth2/start?rd=https://$host$escaped_request_uri
    nginx.ingress.kubernetes.io/auth-url: http://oauth2-proxy-admin.oauth2-proxy.svc.cluster.local/admin/oauth2/auth
    nginx.ingress.kubernetes.io/enable-modsecurity: "true"
    nginx.ingress.kubernetes.io/modsecurity-transaction-id: "$request_id"
    nginx.ingress.kubernetes.io/modsecurity-snippet: |
      SecRuleEngine On
      SecAuditEngine RelevantOnly
      SecAuditLogRelevantStatus "^(?:5|4(?!04))"
      SecAuditLogParts ABIJDEFHZ
      SecAuditLogType Serial
      SecAuditLogFormat JSON
      SecAuditLog /dev/stdout
      SecDebugLog /tmp/modsec_debug.log
      Include /etc/nginx/owasp-modsecurity-crs/nginx-modsecurity.conf
spec:
  ingressClassName: nginx
  rules:
    - host: appdaemon.mdapi.ch
      http:
        paths:
          - backend:
              service:
                name: appdaemon
                port:
                  number: 5050
            path: /
            pathType: Prefix
  tls:
    - hosts:
      - appdaemon.mdapi.ch
      secretName: appdaemon-cert
