apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: appdaemon-env-secret
spec:
  refreshInterval: 1m

  secretStoreRef:
    kind: ClusterSecretStore
    name: cm-akeyless

  target:
    name: appdaemon-env-secret
    creationPolicy: Owner

  data:
    - remoteRef:
        key: /mdapi/appdaemon/appdaemon-env-secret/TOKEN
      secretKey: TOKEN
