apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: appdaemon-secrets-yaml
spec:
  refreshInterval: 1m0s

  secretStoreRef:
    kind: ClusterSecretStore
    name: cm-akeyless

  target:
    name: appdaemon-secrets-yaml
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        secrets.yaml: |
          remocon_username: "{{ .username }}"
          remocon_password: "{{ .password }}"
          remocon_gateway_id: "{{ .gateway_id }}"
          remocon_bearer_token: "{{ .bearer_token }}"

  data:
    - remoteRef:
        key: /mdapi/appdaemon/appdaemon-env-secret/REMOCON_USERNAME
      secretKey: username
    - remoteRef:
        key: /mdapi/appdaemon/appdaemon-env-secret/REMOCON_PASSWORD
      secretKey: password
    - remoteRef:
        key: /mdapi/appdaemon/appdaemon-env-secret/REMOCON_GATEWAY_ID
      secretKey: gateway_id
    - remoteRef:
        key: /mdapi/appdaemon/appdaemon-env-secret/TOKEN
      secretKey: bearer_token
