apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: tsig-secret
spec:
  refreshInterval: 1m

  secretStoreRef:
    kind: ClusterSecretStore
    name: cm-akeyless

  target:
    name: tsig-secret
    creationPolicy: Owner

  data:
    - remoteRef:
        key: /mdapi/appdaemon/tsig-secret/tsig-secret-key
      secretKey: tsig-secret-key
