{{- if and .Values.global.gatewayApi.enabled (eq "true" (include "gitlab.gatewayApi.class.enabled" .)) }}
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: {{ include "gitlab.gatewayApi.class.name" . }}
  labels:
    {{- include "gitlab.standardLabels" . | nindent 4 }}
    {{- include "gitlab.commonLabels" . | nindent 4 }}
    {{- include "gitlab.serviceLabels" . | nindent 4 }}
spec:
  controllerName: {{ .Values.gatewayApiResources.class.controllerName }}
{{- if eq "true" (include "gitlab.gatewayApi.envoy.proxy.enabled" .) }}
  parametersRef:
    group: gateway.envoyproxy.io
    kind: EnvoyProxy
    name: {{ include "gitlab.gatewayApi.envoy.config.name" . }}
    namespace: {{ .Release.Namespace | quote }}
{{- end }}
{{- end }}
