{{- if and .Values.global.kas.enabled .Values.global.kas.tls.enabled }}
{{-   if eq "true" (include "gitlab.gatewayApi.route.enabled" .) -}}
apiVersion: gateway.networking.k8s.io/v1
kind: BackendTLSPolicy
metadata:
  name: {{ template "fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gitlab.standardLabels" . | nindent 4 }}
    {{- include "gitlab.commonLabels" . | nindent 4 }}
spec:
  targetRefs:
  - group: ""
    kind: Service
    name: {{ include "gitlab.kas.serviceName" . | quote }}
  validation:
    {{- $serviceAddress := include "gitlab.assembleServiceAddress" (dict "name" (include "fullname" .) "context" .) }}
    hostname: {{ .Values.backendTLSPolicy.hostname | default $serviceAddress | quote }}
    caCertificateRefs:
    - group: ""
      kind: {{ .Values.backendTLSPolicy.kind | default "Secret" | quote }}
      name: {{ .Values.global.kas.tls.caSecretName | quote }}
{{-   end }}
{{- end }}
