apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: autobrr
  namespace: tv
  annotations:
    cert-manager.io/issuer: letsencrypt-prod
    flame.pawelmalak/type: app
    flame.pawelmalak/name: Announcements
    flame.pawelmalak/url: https://autobrr.mdapi.ch
    flame.pawelmalak/category: TV
    flame.pawelmalak/icon: bell-ring
    flame.pawelmalak/order: '450'
    nginx.ingress.kubernetes.io/auth-response-headers: Authorization
    nginx.ingress.kubernetes.io/auth-signin: https://auth.mdapi.ch/tv/oauth2/start?rd=https://$host$escaped_request_uri
    nginx.ingress.kubernetes.io/auth-url: https://auth.mdapi.ch/tv/oauth2/auth
spec:
  ingressClassName: nginx
  rules:
    - host: autobrr.mdapi.ch
      http:
        paths:
          - backend:
              service:
                name: autobrr
                port:
                  number: 7474
            path: /
            pathType: Prefix
  tls:
    - hosts:
      - autobrr.mdapi.ch
      secretName: autobrr-cert
