apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaresolverr
  namespace: tv
spec:
  selector:
    matchLabels:
      app: flaresolverr
  replicas: 1
  template:
    metadata:
      labels:
        app: flaresolverr
    spec:
      containers:
      - name: flaresolverr
        image: ghcr.io/flaresolverr/flaresolverr
        env:
        - name: TZ
          value: Europe/Zurich
