apiVersion: v1
kind: Service
metadata:
  name: flaresolverr
  namespace: tv
spec:
  selector:
    app: flaresolverr
  ports:
    - name: http
      port: 8191
      protocol: TCP
      targetPort: 8191
  type: ClusterIP
