apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaresolverr
  namespace: tv
  annotations:
    keel.sh/policy: force
    keel.sh/match-tag: "true"
    keel.sh/trigger: poll
    keel.sh/pollSchedule: "@every 4h"
spec:
  selector:
    matchLabels:
      app: flaresolverr
  replicas: 1
  template:
    metadata:
      labels:
        app: flaresolverr
    spec:
      containers:
      - name: flaresolverr
        image: ghcr.io/flaresolverr/flaresolverr:latest
        imagePullPolicy: Always
        env:
        - name: TZ
          value: Europe/Zurich
