apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pia-env-secret
spec:
  refreshInterval: 1m0s

  secretStoreRef:
    kind: ClusterSecretStore
    name: cm-akeyless

  target:
    name: pia-env-secret
    creationPolicy: Owner

  data:
    - remoteRef:
        key: /mdapi/test/tv/pia/pia-env-secret/USER
      secretKey: USER
    - remoteRef:
        key: /mdapi/test/tv/pia/pia-env-secret/PASS
      secretKey: PASS
      
