apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pms-docker-config
spec:
  storageClassName: mdapidev
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pms-docker-transcode
spec:
  storageClassName: mdapidev
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
