apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pms-docker-config
spec:
  storageClassName: harvester-longhorn-2replicas
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pms-docker-transcode-ceph
  labels:
    app.mdapi.ch/phase2: migrated
spec:
  storageClassName: ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
