apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pms-docker
  namespace: tv
  annotations:
    flame.pawelmalak/type: app
    flame.pawelmalak/name: Player
    flame.pawelmalak/url: https://app.plex.tv/web/app/
    flame.pawelmalak/category: TV
    flame.pawelmalak/icon: play
    flame.pawelmalak/order: '10'
spec:
  ingressClassName: nginx
  rules:
    - {}
