apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pms-docker-config
spec:
  storageClassName: harvester-longhorn-2replicas
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pms-docker-transcode
spec:
  storageClassName: harvester-longhorn-2replicas
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
