apiVersion: v1
kind: Service
metadata:
  name: sftpgo
  namespace: tv
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.1.57
  selector:
    app: sftpgo
  ports:
    - { name: sftp,  port: 22200, targetPort: 2022, protocol: TCP }
    - { name: ftp,   port: 22201, targetPort: 2121, protocol: TCP }
    - { name: pasv0, port: 22250, targetPort: 22250, protocol: TCP }
    - { name: pasv1, port: 22251, targetPort: 22251, protocol: TCP }
    - { name: pasv2, port: 22252, targetPort: 22252, protocol: TCP }
    - { name: pasv3, port: 22253, targetPort: 22253, protocol: TCP }
    - { name: pasv4, port: 22254, targetPort: 22254, protocol: TCP }
    - { name: pasv5, port: 22255, targetPort: 22255, protocol: TCP }
    - { name: pasv6, port: 22256, targetPort: 22256, protocol: TCP }
    - { name: pasv7, port: 22257, targetPort: 22257, protocol: TCP }
    - { name: pasv8, port: 22258, targetPort: 22258, protocol: TCP }
    - { name: pasv9, port: 22259, targetPort: 22259, protocol: TCP }
---
apiVersion: v1
kind: Service
metadata:
  name: sftpgo-web
  namespace: tv
spec:
  type: ClusterIP
  selector:
    app: sftpgo
  ports:
    - { name: web, port: 8080, targetPort: 8080, protocol: TCP }
