apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sftpgo-keycloak
  namespace: tv
spec:
  refreshInterval: 1m0s
  secretStoreRef:
    kind: ClusterSecretStore
    name: cm-akeyless
  target:
    name: sftpgo-keycloak
    creationPolicy: Owner
  data:
    - remoteRef:
        key: /mdapi/sftpgo/keycloak-client-secret
      secretKey: KC_CLIENT_SECRET
