apiVersion: apps/v1
kind: Deployment
metadata:
  name: transmission-pia
  namespace: tv
  annotations:
    keel.sh/policy: force
    keel.sh/match-tag: "true"
    keel.sh/trigger: poll
spec:
  selector:
    matchLabels:
      app: transmission-pia
  replicas: 1
  template:
    metadata:
      labels:
        app: transmission-pia
    spec:
      initContainers:
      - name: disable-ipv6
        command:
        - /bin/sysctl
        args:
        - -w
        - net.ipv6.conf.all.disable_ipv6=1
        image: docker.io/busybox
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
      containers:
      - name: transmission
        image: lscr.io/linuxserver/transmission
        ports:
        - containerPort: 9091
        env:
        - name: TZ
          value: Europe/Zurich
        - name: PUID
          value: '1000'
        - name: PGID
          value: '1000'
        volumeMounts:
        - name: transmission-config
          mountPath: /config
        - name: tv
          mountPath: /downloads/complete
          subPath: Torrents/Finish
        - name: tv
          mountPath: /downloads/incomplete
          subPath: Torrents/Temp
        - name: tv
          mountPath: /watch
          subPath: Torrents/Start
      - name: pia
        image: thrnz/docker-wireguard-pia
        env:
        - name: TZ
          value: Europe/Zurich
        - name: LOC
          value: swiss
        - name: LOCAL_NETWORK
          value: '10.0.0.0/8, 192.168.0.0/16, 172.16.0.0/22'
        - name: VPNDNS
          value: '45.90.28.16, 45.90.30.16'
        - name: KEEPALIVE
          value: '25'
        - name: PORT_FORWARDING
          value: '1'
        - name: PORT_PERSIST
          value: '1'
        - name: PORT_FATAL
          value: '1'
        - name: EXIT_ON_FATAL
          value: '1'
        - name: ACTIVE_HEALTHCHECKS
          value: '1'
        - name: HEALTHCHECK_PING_TARGET
          value: '31.3.128.49, test-ipv6.alpinedc.ch'
        - name: RECONNECT
          value: '1'
        - name: POST_UP
          value: 'sleep 10; apk add --no-cache transmission-remote && transmission-remote -p $(cat /pia-shared/port.dat)'
        - name: POST_RECONNECT
          value: 'sleep 10; apk add --no-cache transmission-remote && transmission-remote -p $(cat /pia-shared/port.dat)'
        envFrom:
          - secretRef:
              name: pia-env-secret
        securityContext:
          capabilities:
            add:
              - NET_ADMIN
      volumes:
      - name: transmission-config
        persistentVolumeClaim:
          claimName: transmission-config
      - name: tv
        persistentVolumeClaim:
          claimName: tv
