
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tv-incomplete-ceph
  labels:
    app.mdapi.ch/phase2: migrated
spec:
  storageClassName: ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 250Gi
