apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: jump-authorized-keys
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    kind: ClusterSecretStore
    name: cm-akeyless
  target:
    name: jump-authorized-keys
    creationPolicy: Owner
  data:
    - remoteRef:
        key: /mdapi/jump/authorized-keys/authorized_keys
      secretKey: authorized_keys
