apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: jump-hostkeys
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    kind: ClusterSecretStore
    name: cm-akeyless
  target:
    name: jump-hostkeys
    creationPolicy: Owner
  data:
    - remoteRef:
        key: /mdapi/jump/hostkeys/ssh_host_ed25519_key
      secretKey: ssh_host_ed25519_key
    - remoteRef:
        key: /mdapi/jump/hostkeys/ssh_host_ed25519_key.pub
      secretKey: ssh_host_ed25519_key.pub
    - remoteRef:
        key: /mdapi/jump/hostkeys/ssh_host_rsa_key
      secretKey: ssh_host_rsa_key
    - remoteRef:
        key: /mdapi/jump/hostkeys/ssh_host_rsa_key.pub
      secretKey: ssh_host_rsa_key.pub
