apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cm
  namespace: transit
  annotations:
    cert-manager.io/issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
spec:
  ingressClassName: nginx
  rules:
    - host: cm.home.tillo.ch
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cm
                port:
                  number: 443
  tls:
    - hosts:
        - cm.home.tillo.ch
      secretName: cm-cert
