apiVersion: v1
kind: Endpoints
metadata:
  name: garage
  namespace: transit
subsets:
  - addresses:
      - ip: 192.168.1.207   # salt
      - ip: 192.168.1.219   # pepper
    ports:
      - name: api
        port: 30188
      - name: console
        port: 30186
