udev:
  discovery:
    enabled: true
controller:
  resources:
    requests:
      cpu: 25m
      memory: 128Mi
    limits:
      cpu: 50m
      memory: 192Mi
webhookConfiguration:
  resources:
    requests:
      cpu: 25m
      memory: 128Mi
    limits:
      cpu: 50m
      memory: 192Mi
