apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-ingress-nginx
  namespace: kube-system
spec:
  valuesContent: |-
    controller:
      config:
        allow-snippet-annotations: "true"
        annotations-risk-level: "Critical"
        use-forwarded-headers: "true"
        worker-processes: "4"
      extraArgs:
        tcp-services-configmap: "kube-system/rke2-ingress-nginx-tcp-services"
      containerPort:
        http: 80
        https: 443
        smtp: 25
        subs: 465
        sub: 587
        imaps: 993
