apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mdapidev
parameters:
  type: M1
provisioner: cinder.csi.openstack.org
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: false
