apiVersion: v1
kind: Service
metadata:
  name: frigate
  namespace: frigate
spec:
  selector:
    app: frigate
  ports:
    - name: http
      port: 5000
      protocol: TCP
      targetPort: 5000
    - name: rtsp
      port: 8554
      protocol: TCP
      targetPort: 8554
    - name: go2rtc-api
      port: 1984
      protocol: TCP
      targetPort: 1984
  type: ClusterIP
