apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frigate
  namespace: frigate
  annotations:
    cert-manager.io/issuer: letsencrypt-prod
    flame.pawelmalak/type: app
    flame.pawelmalak/name: NVR (dev)
    flame.pawelmalak/url: https://frigate.dev.mdapi.ch
    flame.pawelmalak/category: Domotics
    flame.pawelmalak/icon: cctv
    flame.pawelmalak/order: '50'
spec:
  ingressClassName: nginx
  rules:
    - host: frigate.dev.mdapi.ch
      http:
        paths:
          - backend:
              service:
                name: frigate
                port:
                  number: 5000
            path: /
            pathType: Prefix
  tls:
    - hosts:
      - frigate.dev.mdapi.ch
      secretName: frigate-cert
