apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frigate-config
spec:
  storageClassName: harvester-longhorn-2replicas
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frigate-media
spec:
  storageClassName: harvester-longhorn-2replicas
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
