apiVersion: apps/v1
kind: Deployment
metadata:
  name: autoconfig
  namespace: mail
  annotations:
    keel.sh/policy: force
    keel.sh/match-tag: "true"
    keel.sh/trigger: poll
    keel.sh/pollSchedule: "@every 4h"
spec:
  selector:
    matchLabels:
      app: autoconfig
  replicas: 2
  template:
    metadata:
      labels:
        app: autoconfig
    spec:
      priorityClassName: mdapi-critical
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchLabels:
                  app: autoconfig
              topologyKey: kubernetes.io/hostname
      containers:
      - name: autoconfig
        image: registry.mdapi.ch/mdapi/autoconfig:latest
        imagePullPolicy: Always
        resources: {}
        ports:
        - containerPort: 80
          protocol: TCP
        env:
        - name: TZ
          value: Europe/Zurich
        - name: MAIL_HOSTNAME
          value: mail.mdapi.ch
        - name: DISPLAY_NAME
          value: "Martino Dell'Ambrogio Personal Infrastructure"
        - name: DISPLAY_SHORT_NAME
          value: MDAPI
      imagePullSecrets:
      - name: mdapi-registry
