apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mail-cert
  namespace: mail
spec:
  dnsNames:
    - 'mail.mdapi.ch'
  issuerRef:
    kind: Issuer
    name: letsencrypt-prod
  secretName: mail-cert
