apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: roundcube
  namespace: mail
  annotations:
    cert-manager.io/issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/server-alias: "webmail.coders.ch,webmail.coiffuredreams.ch,webmail.dellambrogio.ch,webmail.textopolis.net,webmail.tillo.ch,webmail.lithia.eu"
    nginx.ingress.kubernetes.io/enable-modsecurity: "true"
    nginx.ingress.kubernetes.io/modsecurity-transaction-id: "$request_id"
    nginx.ingress.kubernetes.io/modsecurity-snippet: |
      SecRuleEngine On
      SecDebugLog /tmp/modsec_debug.log
      Include /etc/nginx/owasp-modsecurity-crs/nginx-modsecurity.conf
spec:
  ingressClassName: nginx
  rules:
    - host: webmail.mdapi.ch
      http:
        paths:
          - backend:
              service:
                name: roundcube
                port:
                  number: 80
            path: /
            pathType: Prefix
  tls:
    - hosts:
      - webmail.mdapi.ch
      - webmail.coders.ch
      - webmail.coiffuredreams.ch
      - webmail.dellambrogio.ch
      - webmail.textopolis.net
      - webmail.tillo.ch
      - webmail.lithia.eu
      secretName: webmail-cert
