apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: salt-nfs-driver-config
spec:
  refreshInterval: 1m0s

  secretStoreRef:
    kind: ClusterSecretStore
    name: cm-akeyless

  target:
    name: salt-nfs-driver-config
    creationPolicy: Owner
    template:
      data:
        driver-config-file.yaml: '{{ .saltNfsDriverConfig | toString }}'

  data:
    - remoteRef:
        key: /mdapi/democratic-csi/salt-nfs-driver-config
      secretKey: saltNfsDriverConfig
