apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: docs-mdapi-ch-cert
  namespace: bootstrap
spec:
  secretName: docs-mdapi-ch-cert
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - docs.mdapi.ch
