apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: esphome-env-secret
spec:
  refreshInterval: 1m

  secretStoreRef:
    kind: ClusterSecretStore
    name: cm-akeyless

  target:
    name: esphome-env-secret
    creationPolicy: Owner

  data:
    - remoteRef:
        key: /mdapi/esphome/esphome-env-secret/USERNAME
      secretKey: USERNAME
    - remoteRef:
        key: /mdapi/esphome/esphome-env-secret/PASSWORD
      secretKey: PASSWORD
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: esphome-secrets
spec:
  refreshInterval: 1m

  secretStoreRef:
    kind: ClusterSecretStore
    name: cm-akeyless

  target:
    name: esphome-secrets
    creationPolicy: Owner

  data:
    - remoteRef:
        key: /mdapi/esphome/esphome-secrets/secrets.yaml
      secretKey: secrets.yaml
