apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: grafana-ingress
spec:
  type: ExternalName
  externalName: rancher-monitoring-grafana.cattle-monitoring-system.svc.cluster.local
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
